# Generated by Django 5.0 on 2025-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0003_tarea_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
