# Generated by Django 5.0 on 2025-08-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0004_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referido',
            name='referido',
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='aceptar_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='captura_pago',
            field=models.ImageField(blank=True, null=True, upload_to='capturas/'),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptodeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referido',
            name='referidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_invertidos', related_query_name='referidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
