# Generated by Django 5.0 on 2025-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0006_cryptodeposit_retries_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodeposit',
            name='aceptar_terminos',
        ),
        migrations.RemoveField(
            model_name='cryptodeposit',
            name='invoice_url',
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
