# Generated by Django 5.0 on 2025-08-15 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0007_remove_cryptodeposit_aceptar_terminos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('address', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
