# Generated by Django 5.0 on 2025-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0008_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='amount_usd',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
